[DAY-11] Day 11 Challenge
Pxyzi3c/AWSCC-CodeQuest-Backend pull request #9
Opened 2024-02-05 04:54 UTC by Pxyzi3c

**PROBLEM DESCRIPTION**
In a text file, provide students with a list of names, one name per line. Ask them to create a Python program that reads the names, sorts them alphabetically, and writes the sorted names back to the file.

**HINT**
You can read the names from the file using the `.readlines()` method. This function reads each line in the file and returns a list of lines, making it easier to work with line-based data. To write the sorted names back to the file, consider using the `.writelines()` method, which allows you to write a list of strings back to the file.

2024-02-05 09:33 UTC, Pxyzi3c commented on backend/day-12/day-12-challenge.py
Pa disregard na lang toh yah. Sa day 12 toh kala ko may challenge eh hehe.

2024-02-10 07:15 UTC, theadg requested changes
Good shit

2024-02-10 07:15 UTC, theadg commented on backend/day-11/day-11-challenge.py
> +        print("File does not exists!")
typo on exists?

2024-02-12 10:21 UTC, Pxyzi3c commented on backend/day-11/day-11-challenge.py
> +        print("File does not exists!")
I don't think so

2024-02-13 10:52 UTC, theadg approved these changes

2024-02-15 13:56 UTC, merged